server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: CorrectPass
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

